"""
Marcas de referencia frecuentes en repuestos (Chile / Latam).
El usuario puede escribir cualquier otra; esto solo alimenta sugerencias (datalist).
Lista ampliada con OEM, aftermarket y lubricantes habituales en importación chilena.
"""

from __future__ import annotations

# Nombres en MAYÚSCULAS para alinear con _normalize_brand del módulo bodega.
MARCAS_REF_AUTOMOTRIZ_CL: frozenset[str] = frozenset(
    {
        # —— OEM / armadoras (muy usadas como variante o línea en Chile) ——
        "ACURA",
        "ALFA ROMEO",
        "ASTON MARTIN",
        "AUDI",
        "BAIC",
        "BMW",
        "BYD",
        "CADILLAC",
        "CHANGAN",
        "CHERY",
        "CHEVROLET",
        "CHRYSLER",
        "CITROEN",
        "CUPRA",
        "DACIA",
        "DAEWOO",
        "DAIHATSU",
        "DODGE",
        "DS",
        "FAW",
        "FERRARI",
        "FIAT",
        "FORD",
        "FOTON",
        "GAC",
        "GEELY",
        "GREAT WALL",
        "HAVAL",
        "HINO",
        "HOLDEN",
        "HONDA",
        "HUMMER",
        "HYUNDAI",
        "INEOS",
        "INFINITI",
        "ISUZU",
        "IVECO",
        "JAC",
        "JAGUAR",
        "JEEP",
        "JMC",
        "KIA",
        "LADA",
        "LAMBORGHINI",
        "LANCIA",
        "LAND ROVER",
        "LEXUS",
        "LIFAN",
        "LOTUS",
        "MAHINDRA",
        "MAN",
        "MASERATI",
        "MAXUS",
        "MAZDA",
        "MCLAREN",
        "MERCEDES BENZ",
        "MERCEDES-BENZ",
        "MG",
        "MINI",
        "MITSUBISHI",
        "NISSAN",
        "OPEL",
        "PEUGEOT",
        "POLESTAR",
        "PORSCHE",
        "RAM",
        "RENAULT",
        "ROLLS ROYCE",
        "ROVER",
        "SAAB",
        "SCANIA",
        "SEAT",
        "SKODA",
        "SMART",
        "SSANGYONG",
        "SUBARU",
        "SUZUKI",
        "TATA",
        "TESLA",
        "TOYOTA",
        "UAZ",
        "VOLKSWAGEN",
        "VOLVO",
        "WEY",
        "ZNA",
        "ZX AUTO",
        # —— Aftermarket / repuestos (Europa, USA, Asia) ——
        "ACDELCO",
        "ADVICS",
        "AKEBONO",
        "AISIN",
        "AJUSA",
        "AMC",
        "APPLUS",
        "ASHIKA",
        "ATE",
        "AUTLOG",
        "AUTOTEAM",
        "AVS",
        "BANDO",
        "BENDIX",
        "BERU",
        "BILSTEIN",
        "BLUE PRINT",
        "BORG WARNER",
        "BORGWARNER",
        "BOSCH",
        "BREMBO",
        "BRISK",
        "BTS TURBO",
        "CALORSTAT",
        "CHAMPION",
        "CIFAM",
        "CORTECO",
        "CTR",
        "DAYCO",
        "DELCO REMY",
        "DELPHI",
        "DENSO",
        "DOLZ",
        "DONALDSON",
        "ELRING",
        "EXEDY",
        "FACET",
        "FAE",
        "FAG",
        "FEBI",
        "FEBI BILSTEIN",
        "FERODO",
        "FILTRON",
        "FRAM",
        "GABRIEL",
        "GALFER",
        "GARRETT",
        "GATES",
        "GLASER",
        "GOETZE",
        "GRAF",
        "HELLA",
        "HEPU",
        "HENGST",
        "HITACHI",
        "HUTCHINSON",
        "IHI",
        "INA",
        "JAPANPARTS",
        "JOHNS",
        "JS ASAKASHI",
        "JURID",
        "KAGER",
        "KOLBENSCHMIDT",
        "KNECHT",
        "KLARIUS",
        "KOYO",
        "KYB",
        "LEMFORDER",
        "LEMFOERDER",
        "LIPE",
        "LPR",
        "LUK",
        "LYNXAUTO",
        "MAGNETI MARELLI",
        "MAHLE",
        "MANN",
        "METALCAUCHO",
        "METELLI",
        "METZGER",
        "MINTEX",
        "MOOG",
        "MONROE",
        "MOTORCRAFT",
        "MOTUL",
        "NRF",
        "NSK",
        "NTN",
        "NGK",
        "OSRAM",
        "PATRON",
        "PAYEN",
        "PHILIPS",
        "PIERBURG",
        "PURFLUX",
        "RCPS",
        "RECORD",
        "REINZ",
        "REMSA",
        "RUVILLE",
        "SACHS",
        "SAKURA",
        "SANDEN",
        "SCHRADER",
        "SIDEM",
        "SIEMENS",
        "SKF",
        "SNR",
        "SOFIMA",
        "SOGEFI",
        "STANDARD",
        "STELLOX",
        "SWAG",
        "TEXTAR",
        "TIMKEN",
        "TOPRAN",
        "TRW",
        "UFI",
        "VALEO",
        "VAN WEZEL",
        "VARTA",
        "VDO",
        "VICTOR REINZ",
        "WALKER",
        "WAHLER",
        "WILLARD",
        "WIX",
        "ZF",
        # —— Lubricantes y fluidos (muy presentes en Chile) ——
        "AMALIE",
        "CASTROL",
        "ELF",
        "FUCHS",
        "IPSA",
        "KENDALL",
        "LIQUI MOLY",
        "LUBRAX",
        "MOBIL",
        "PENNZOIL",
        "PETROBRAS",
        "PETRONAS",
        "QUAKER STATE",
        "REPSOL",
        "ROYAL PURPLE",
        "SHELL",
        "TOTAL",
        "VALVOLINE",
        "YPF",
        # —— Neumáticos y accesorios frecuentes ——
        "BARUM",
        "BRIDGESTONE",
        "CONTINENTAL",
        "COOPER",
        "DUNLOP",
        "FALKEN",
        "FIRESTONE",
        "GITI",
        "GOODYEAR",
        "HANKOOK",
        "KUMHO",
        "LINGLONG",
        "MICHELIN",
        "NEXEN",
        "PIRELLI",
        "TOYO",
        "YOKOHAMA",
        "STP",
        "WURTH",
        # —— Marcas alternativas / económicas habituales en importación ——
        "AUTOKIT",
        "BAPMIC",
        "BREMI",
        "CARQUEST",
        "DORMAN",
        "DTS",
        "EQUAL QUALITY",
        "EUROREPAR",
        "FENOX",
        "FIT",
        "GSP",
        "HANSPRIES",
        "IPS PARTS",
        "JAPKO",
        "KAMOKA",
        "KRAFT AUTOMOTIVE",
        "LYNX",
        "MAPCO",
        "MAXGEAR",
        "MEYLE",
        "MILES",
        "NIPPARTS",
        "NK",
        "OPEN PARTS",
        "OPTIMAL",
        "PARTS-MALL",
        "PRASCO",
        "PROFIT",
        "QUINTON HAZELL",
        "RBI",
        "RIDEX",
        "RTS",
        "SBS",
        "SCT",
        "STARLINE",
        "TYC",
        "VAICO",
        "WAI GLOBAL",
        "WILMINK GROUP",
        "WIX FILTERS",
    }
)
